### ISSUE TITLE
[Question]: How to debug "Process exited"

### ISSUE THREAD

**Issue by JenyaRostov** [microsoft/playwright-dotnet#2641] opened 2023-07-17 22:48 UTC
### Your question

Sometimes i get "Microsoft.Playwright.PlaywrightException: Process exited" exception and my question is how do i debug the cause of it? I'm using mozilla
I tried setting debug environment variable for mozilla but logs came out empty

**Comment by mxschmitt** [comment] 2023-07-19 14:18
Hey! This error means that the underlying driver which Playwright for .NET exited. Stderr of the driver should already get forwarded to your process, so any errors there should be shown. Also you can see the stdout by setting the `DEBUG=pw:channel:response,pw:channel:event` environment variable. This should give us some hints whats going on.

**Comment by JenyaRostov** [comment] 2023-07-19 20:12
Hello! I tried that and i got this
![image](https://i.imgur.com/wIlZoEl.png)

**Comment by mxschmitt** [comment] 2023-07-20 16:11
This looks like the driver is sending something and the client can't parse it. Can you also try to set these environment variable? Is it reproducible all the time? Can you share a repro?

`DEBUG=pw:channel:response,pw:channel:event,pw:channel:command`

**Comment by JenyaRostov** [comment] 2023-07-20 17:03
I think it sends an incomplete json? There's also this
![](https://i.imgur.com/tuMY53S.png)
Setup is pretty convoluted and has some private info but i'll see if i can make a bare repro
Will also report if i find anything new with this env variable

**Comment by mxschmitt** [comment] 2023-07-31 11:57
Closing as part of the triage process since we don't have a minimal repro. Feel free to re-file if you have a repro, thanks!

**Closed by mxschmitt** 2023-07-31 11:57 UTC
Labels: triaging

**Comment by xbaha** [comment] 2023-08-21 19:27
I am getting the same error: Microsoft.Playwright.PlaywrightException: 'Process exited'
It's random and can not be reproduced, it works for weeks,, and suddenly it doesn't. and when I restart it, it works again on the same URLs. there is no pattern or specific URL.
The problem is that it forces my app to stop, even though the playwright is within try-catch, but the whole program gets terminated, i hope at least fix it so that it gets caught and I can re-fetch the URLs again!

**Comment by arashberlin** [comment] 2024-09-10 16:43
> I am getting the same error: Microsoft.Playwright.PlaywrightException: 'Process exited' It's random and can not be reproduced, it works for weeks,, and suddenly it doesn't. and when I restart it, it works again on the same URLs. there is no pattern or specific URL. The problem is that it forces my app to stop, even though the playwright is within try-catch, but the whole program gets terminated, i hope at least fix it so that it gets caught and I can re-fetch the URLs again!

Hey did you find any solution?  

My .NET app on the production server is throwing the exception Microsoft.Playwright.PlaywrightException: 'Process exited'.

I don't have any issues on my local machine or the staging environment. The service account has full control over the root drive and execute rights on the Node.js installation folder.

I am using Playwright Version 1.46.0

Am I missing something? A couple of months ago, I didn't have these issues.

I also have the same problem with Puppeteer Sharp.

Thanks, 

Arash
