### ISSUE TITLE
[BUG]: .NET Framework 4.8 Driver not found in Temporary ASP.NET Files

### ISSUE THREAD

**Issue by BeniFreitag** [microsoft/playwright-dotnet#2240] opened 2022-08-05 09:02 UTC
**Context:**
- Playwright Version: 1.24.1
- Operating System: Windows 11 (and Windows Server 2019)
- .NET version: .NET 4.8
- Browser: All

**Code Snippet**

Sample-Project with ASP.Net Website and ASP.Net Webapplication at https://github.com/BeniFreitag/Playwright-AspNet-4.8

**Describe the bug**

Followup of #1842 and #1872. When the ASP.Net Application runs, DLLs are copied to _Temporary ASP.NET Files_ automatically. [`Microsoft.Playwright.Helpers.Driver.GetExecutablePath()`](https://github.com/microsoft/playwright-dotnet/blob/main/src/Playwright/Helpers/Driver.cs#L35-L58) looks for a .playwright folder there, but the ASP.NET ecosystem/runtime doesn't copy this folder to _Temporary ASP.NET Files_, so it always fails with error:

```
Driver not found: C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\vs\6c77f81d\ac62943a\assembly\dl3\.playwright\node\win32_x64\playwright.cmd

Stack Trace:
[PlaywrightException: Driver not found: C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\vs\6c77f81d\ac62943a\assembly\dl3\.playwright\node\win32_x64\playwright.cmd]
   Microsoft.Playwright.Helpers.Driver.GetExecutablePath() in /_/src/Playwright/Helpers/Driver.cs:57
   Microsoft.Playwright.Transport.StdIOTransport.GetProcess() in /_/src/Playwright/Transport/StdIOTransport.cs:119
   Microsoft.Playwright.Transport.StdIOTransport..ctor() in /_/src/Playwright/Transport/StdIOTransport.cs:44
   Microsoft.Playwright.<CreateAsync>d__0.MoveNext() in /_/src/Playwright/Playwright.cs:44
   System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +32
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +62
   System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() +32
   ClassLibrary.<GetPdf>d__0.MoveNext() in C:\Projects\Playwright-AspNet-4.8\ClassLibrary\PdfService.cs:11
   System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +32
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +62
   System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() +32
   <GeneratePdf>d__0.MoveNext() in c:\Projects\Playwright-AspNet-4.8\Website\Default.aspx.cs:17
   System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +32
   System.Web.UI.<ExecuteTasksAsync>d__3.MoveNext() +450
   System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() +32
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +62
   System.Web.UI.<ProcessRequestAsync>d__554.MoveNext() +981
```

**Suggestion**
Please provide an option to specify the location of the .playwright-folder, as mentioned in https://github.com/microsoft/playwright-dotnet/issues/1842#issuecomment-1085161889:
```c#
Playwright.CreateAsync(driverExecutablePath: "...");
```
or via an environment-variable e.g. [PLAYWRIGHT_BROWSERS_PATH](https://github.com/microsoft/playwright-dotnet/issues/1842#issuecomment-1034480531)

**Comment by mxschmitt** [comment] 2022-08-05 11:30
ASP .NET projects are using packages.config, so its related/dupe of https://github.com/microsoft/playwright-dotnet/issues/2004.

**Closed** 2022-08-05 12:08 UTC

**Comment by mxschmitt** [comment] 2022-08-23 10:17
@BeniFreitag from the next release onwards we support net framework out of the box, sorry for the delay!

**Comment by BeniFreitag** [comment] 2022-09-13 10:31
Just tested it successfully in 1.27.0-beta with ASP.NET 4.8 🚀. Thanks!
