### ISSUE TITLE
[Feature]: Add BrowserType.ConnectOverCDP(endpointURL[, options]) for .NET

### ISSUE THREAD

**Issue by Andrei-Sav** [microsoft/playwright-dotnet#1678] opened 2021-08-12 21:26 UTC
### Feature request

Add BrowserType.ConnectOverCDP(endpointURL[, options]) for .NET like other versions have

**Comment by mxschmitt** [comment] 2021-08-13 17:34
Closing as duplicate of #1291.

**Closed by mxschmitt** 2021-08-13 17:34 UTC
