### ISSUE TITLE
Throws exception from `request.SizesAsync()`

### ISSUE THREAD

**Issue by lonix1** [microsoft/playwright-dotnet#2743] opened 2023-11-02 15:10 UTC
I need to know the network traffic for requests and responses.

So following Max's [advice here](https://github.com/microsoft/playwright/issues/11438), I did this:
```cs
var page = await browserContext.NewPageAsync();
page.Request  += (_, request)  => MeasureBandwidth(request);
page.Response += (_, response) => MeasureBandwidth(response.Request);

// ...

private async void MeasureBandwidth(IRequest request) {
  var sizes = await request.SizesAsync();
  _totalTraffic += sizes.RequestHeadersSize + sizes.RequestBodySize + sizes.ResponseHeadersSize + sizes.ResponseBodySize;
}
```

That's an async void event handler, which is the one place such an async void is appropriate. Although that works, sometimes it throws [an exception](https://github.com/microsoft/playwright-dotnet/blob/530809455f5a178876a73faa0e49c3b4bfc75382/src/Playwright/Core/Request.cs#L182):
> Unable to fetch resources sizes

Why does that happen?

(Also, if that method is expected to throw, then it should be documented with a `/// <exception cref="PlaywrightException">....</exception>` otherwise there's no way to know until your app blows up.)

**Comment by mxschmitt** [comment] 2023-11-07 09:08
This exception gets thrown when there was a request in-flight and the page was getting closed. So we recommend catching it like this:

```csharp
using Microsoft.Playwright;

using var playwright = await Playwright.CreateAsync();
await using var browser = await playwright.Chromium.LaunchAsync();
var page = await browser.NewPageAsync();

var _totalTraffic = 0;
async void MeasureBandwidth(IRequest request)
{
    try
    {
        var sizes = await request.SizesAsync();
        _totalTraffic += sizes.RequestHeadersSize + sizes.RequestBodySize + sizes.ResponseHeadersSize + sizes.ResponseBodySize;
    }
    catch (PlaywrightException)
    {
        // Ignore network failures and in-flight requests that got canceled on page close.
    }
}

page.Request += (_, request) => MeasureBandwidth(request);

```

You are also attaching the listener twice, you only need to attach it once, since `request === response.Request`.

**Comment by mxschmitt** [comment] 2023-11-13 16:16
"Pipe is broken." and NullReferenceException  should never happen. If you have a repro for that, let us know, we have not seen this one before.

We usually don't document exceptions. In a nutshell all Playwright methods can throw target closed errors, which will happen in this case from the next release on. Page.click e.g. when a page is about to close etc.

Closing as per above then, if you have a minimal reproduction, feel free to re-file, thanks!

**Closed by mxschmitt** 2023-11-13 16:16 UTC
Labels: triaging
