### ISSUE TITLE
[BUG] Recording saves one extra video with no lenght

### ISSUE THREAD

**Issue by Hocejeking** [microsoft/playwright-dotnet#2647] opened 2023-07-24 10:30 UTC
**Context:**
- Playwright Version: 1.35.0
- Operating System: Win 11
- .NET version: NET 6.0
- Browser: Chromium

**Code Snippet**

A simple test solution, that mimics the real situation.

```namespace UITests.Web;

[TestFixture]
public class Session : PageTest
{
    public static string DataDirectory => System.Environment.GetEnvironmentVariable("DefaultDataDirectory") ?? "TestsOutput";

    public override BrowserNewContextOptions ContextOptions()
    {
        BrowserNewContextOptions contextOptions = new BrowserNewContextOptions();

        contextOptions.Locale = "cs-CZ";
        contextOptions.RecordVideoDir = Path.Combine(DataDirectory, Constants.System.Directories.Videos);

        return contextOptions;
    }

    [Test, Order(1)]
    public async Task Login()
    {
        await Page.GotoAsync("https://gw.logeto.com");

        await Page.Locator(Constants.Account.Register.Account).FillAsync("xxxxxxxx");
        await Page.Locator(Constants.Account.Register.Continue).ClickAsync();
        await Page.Locator(Constants.Account.Register.Email).FillAsync("xxxxxx@xxxxxxxx.cz");
        await Page.Locator(Constants.Account.Register.Password).FillAsync("xxxxxx");
        await Page.Locator(Constants.Account.Register.Continue).ClickAsync();
        await Page.Locator("id=logoutButton").WaitForAsync();

        await Context.StorageStateAsync(new() { Path = "state.json" });
    }
}
```

**Describe the bug**
After using the StorageStateAsync() method, there would be 2 videos created in the specified directory. The first one would be the real video, that works normally. The other video, would have no length and would show nothing - this issue would repeat for all subsequent videos that would be potentially created, each one creating a clone that is "almost empty."

I have attached the created file of the second video for clarification.
[53b01fb6179a0bcfe34eef8cede1c543.webm](https://github.com/microsoft/playwright-dotnet/assets/53022454/bc79a9f1-d894-4996-898d-6c899546f0ca)

**Comment by mxschmitt** [comment] 2023-07-24 13:02
This is a duplicate of https://github.com/microsoft/playwright/issues/6743.

The reason for that is that we internally create a page when saving the storageState(). You can workaround it by saving the video via save() see [here](https://playwright.dev/python/docs/videos#record-video), so not all the pages get saved to disk and you can manually decide which ones to save. -> only the main frames.

**Closed by mxschmitt** 2023-07-24 13:02 UTC

**Comment by Hocejeking** [comment] 2023-07-25 08:00
Thank you for answering @mxschmitt, although I have some follow up questions. You provided a link to Python documentation, so I am going to assume that you meant using the `Page.Video.SaveAsAsync()` method.

I am not able to figure out how to use this method correctly.  In the the docs, it is clearly stated that 

> This method waits until the page is closed and the video is fully saved.

However, this is not the ideal solution as I **cannot** wait for the page to close. Would you be able to provide any other workarounds ? I really do think this issue is something that should not be looked over, as it can get very annoying when running a large amount of tests and then having to filter out the videos.

Thank you.

**Comment by mxschmitt** [comment] 2023-07-26 13:18
Oh sorry, for .NET its similar, see [here](https://playwright.dev/dotnet/docs/videos). Yes with the base classes the integration is not trivial or not possible yet, see https://github.com/microsoft/playwright-dotnet/issues/2214.

If you want to have everything working out of the box, we recommend Playwright for .NET for now.
