### ISSUE TITLE
[Question]: Proper usage of ToHaveAttributeAsync() with Not

### ISSUE THREAD

**Issue by abdushaj** [microsoft/playwright-dotnet#2243] opened 2022-08-09 14:14 UTC
### Your question

Curious to know if the Assertions.Expect(locator).Not.ToHaveAttributeAsync("expanded", string.Empty) works as it should be.

Scenario is with a collapable accordion element with attribute `expanded` without any value

- when exapanded element will have `expanded` attribute
- when collapse element will not have `expanded` attribute 

And am I using it right - to check if element is collapsed?

`Assertions.Expect(locator).Not.ToHaveAttributeAsync("expanded", string.Empty)`

Exception log :
`Microsoft.Playwright.PlaywrightException: Locator expected not to have attribute 'expanded' ''
But was: ''`

Currently I'm ensuring this by having an extra check with 
`Assertions.Expect(locator).ToHaveAttributeAsync("expanded", string.Empty);
locator.GetAttributeAsync(attributeName).Result.Should().BeNull($"Attribute '{attributeName}' is expected not to be present!");`

**Comment by mxschmitt** [comment] 2022-08-09 14:49
Duplicate of https://github.com/microsoft/playwright-dotnet/issues/2243.

**Closed by mxschmitt** 2022-08-09 14:49 UTC
