### ISSUE TITLE
[Question]: Possible reasons for a choppy video?

### ISSUE THREAD

**Issue by Konnor5092** [microsoft/playwright-dotnet#1642] opened 2021-07-27 15:49 UTC
### Your question

I'm experiencing an issue with video recording only when running Playwright on a macOS X Catalina 10.15 build agent.

The video is very choppy and it's not possible to make out what the test is doing...

![image](https://user-images.githubusercontent.com/18048889/127184246-bbc4e6d8-402f-4039-b5b0-c709e7de5785.png)

It's a Chromium test ran with the 'Pixel 5' device settings.

Any ideas on what could be causing this?

I've ran this same test on Windows 10 and macOS Bug Sur (Intel) without any issues with the resultant video. I can't find the spec of the build agent nor can I connect to any sort of a GUI. It's likely though the specs on the working machines are significantly better than the build agent. Could this be the cause?

Many thanks,

**Comment by avodovnik** [comment] 2021-07-28 08:52
Which version of Playwright for .NET are you using?
What build agents/build system are you using?

**Comment by Konnor5092** [comment] 2021-07-28 09:14
I'm using 1.13.0. 
The build agent is an Azure Devops hosted [macOS-10.15](https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md)

**Comment by mxschmitt** [comment] 2021-11-17 21:08
Closing since its most likely not related to Playwright .NET and we can't reproduce it. If you have a reproducible, let us know!

**Closed by mxschmitt** 2021-11-17 21:08 UTC
Labels: triaging
