### ISSUE TITLE
[BUG] Playwright for .net is not uploading file even code generated by codegen is also not working

### ISSUE THREAD

**Issue by thisisnewbi** [microsoft/playwright-dotnet#2452] opened 2023-01-16 17:08 UTC
**Context:**
- Playwright Version: [Microsoft.Playwright.NUnit 1.29.0]
- Operating System: [e.g. Windows, Linux ]
- .NET version: [ .NET 6]
- Browser: [All, Chromium, Firefox, ]
- Extra: [any specific details about your environment]

**Code Snippet**

            // var fileChooser = await _pageObject.Page.RunAndWaitForFileChooserAsync(async () =>
            // {

            //     await _pageObject.Page.Locator("//span[text()='Upload Cost']").ClickAsync();
            

            // });
            // await _pageObject.Page.WaitForFileChooserAsync();
           
            //await fileChooser.SetFilesAsync("Config.xlsx");

![image](https://user-images.githubusercontent.com/59443858/212732988-2f46ca75-6a9e-4527-acd7-4557fd4d76ac.png)

**Describe the bug**
 In my webpage there is one upload button and that triggers input button in backend which is hidden from the library perspective refer attached image.  I tried using setinput file directly but that didnt work so i tried runandwaitforfilechooser but to my avail this also didnt work.
Also I tried codegen and that is also generating code which is literally wrong!(Refer code below)
await page.GetByRole(AriaRole.Button, new() { Name = "⭫ Upload Cost" }).ClickAsync();
 await page.GetByRole(AriaRole.Button, new() { Name = "⭫ Upload Cost" }).SetInputFilesAsync(new[] { "ConfigCost.xlsx" });
Add any other details about the problem here.

**Comment by thisisnewbi** [comment] 2023-01-22 16:48
Can anyone help me here ?

**Comment by mxschmitt** [comment] 2023-01-23 12:52
```csharp
        var fileChooser = await _pageObject.Page.RunAndWaitForFileChooserAsync(async () =>
        {
             await _pageObject.Page.Locator("//span[text()='Upload Cost']").ClickAsync();
        });
        await _pageObject.Page.WaitForFileChooserAsync();
```

this code looks good, where is it failing? Whats the error message?

**Comment by thisisnewbi** [comment] 2023-01-23 14:30
There is no error message that gets displayed and it doesnt open the file explorer either with above code
so i updated the code where i had to click on the button twice in filechooser post which filechooser gets opened 
 var fileChooser = await _pageObject.Page.RunAndWaitForFileChooserAsync(async () =>
            {

                await _pageObject.Page.Locator("//span[text()='Upload Cost']").ClickAsync();

              await _pageObject.Page.Locator("//span[text()='Upload Cost']").ClickAsync();
            });

but than in wait for filechooser i get this error Timeout 90000ms exceeded while waiting for event "FileChooser"

**Comment by thisisnewbi** [comment] 2023-01-23 14:35
let me know if you need any screenshots

**Comment by mxschmitt** [comment] 2023-01-23 14:50
So looks like no file chooser gets opened. Can you share a repro with us?

**Comment by thisisnewbi** [comment] 2023-01-23 15:05
repro means ?

**Comment by thisisnewbi** [comment] 2023-01-24 06:44
Please do let me know if you need any further details as this scenario is an imp one for me to highlight playwright in our proj

**Comment by mxschmitt** [comment] 2023-01-26 15:43
Repro means a full reproduction which we can run locally which demonstrates the issue. Sharing only the DOM does not help unfortunately.

**Comment by resah** [comment] 2023-01-30 12:58
Is the file input itself hidden and the button is actually handling the file chooser?
If yes, then your code snippet should look something like that:

```
        var fileChooser = await _pageObject.Page.RunAndWaitForFileChooserAsync(async () =>
        {
             await _pageObject.Page.Locator("//span[text()='Upload Cost']").ClickAsync();
        });
        await fileChooser.SetFilesAsync("path/to/file.pdf");
```
Note, that you need to give an actual file from the file system.

If the button handles the form interaction and the file input itself is visible, you could just use 

```
await _pageObject.Page.Locator("#formFile").SetInputFilesAsync("path/to/file.pdf");
```

**Comment by mxschmitt** [comment] 2023-02-01 14:20
Closing as part of the triage process and we don't have a clear repro so we cannot act on it. Please re-file with a clear reproduction.

**Closed by mxschmitt** 2023-02-01 14:20 UTC
Labels: triaging

**Comment by rbauduin** [comment] 2023-03-09 08:50
I had the same problem, and I think the problem comes because there should be no `await` when calling `RunAndWaitForFileChooserAsync`. This is hinted at in the [js version docs](https://playwright.dev/docs/api/class-filechooser).
I'm working in FSharp. This code didn't work, meaning the file chooser event never fired:
```
        // The let! here is equivalent to using await
        let! fileChooserPromise =
            page.RunAndWaitForFileChooserAsync(
                fun () -> task{
                    do! page.ClickAsync($"""{xPathForFormFieldContainerFromLabel "logo"}//input""")
                }
            )
        do! fileChooser.SetFilesAsync("fixtures/files/attachments/logo-small.png")
```
However, this code works fine:
```
        let fileChooserPromise =
            page.RunAndWaitForFileChooserAsync(
                fun () -> task{
                    do! page.ClickAsync($"""{xPathForFormFieldContainerFromLabel "logo"}//input""")
                }
            )
        let! fileChooser = fileChooserPromise
        do! fileChooser.SetFilesAsync("fixtures/files/attachments/logo-small.png")
```
I never wrote any C#, but I think something like this will probably work:
```
        // Note: no await here
        var fileChooserPromise = _pageObject.Page.RunAndWaitForFileChooserAsync(async () =>
        {
             await _pageObject.Page.Locator("//span[text()='Upload Cost']").ClickAsync();
        });
        var fileChooser = await fileChoosePromise;
        await _pageObject.Page.WaitForFileChooserAsync();
```
