### ISSUE TITLE
[BUG]playwright Memory Leak

### ISSUE THREAD

**Issue by bba2022** [microsoft/playwright-dotnet#2846] opened 2024-01-26 17:14 UTC
### System info
- Playwright Version: [v1.41]
- Operating System: [Windows 11]
- Browser: [Chromium]
- Other info:

### Source code

- [ ] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

https://github.com/bba2022/playwrightTest

using Microsoft.Playwright;
using System.Collections.Concurrent;
using System.Net;

namespace playwrightTest
{
    internal class Program
    {
       
        static void Main(string[] args)
        {
            _ = testAsync();
            Console.ReadKey();
        }
        public static async Task testAsync() {
            try
            {
                var playwright = await Playwright.CreateAsync();
                BrowserTypeLaunchPersistentContextOptions options = new BrowserTypeLaunchPersistentContextOptions();
                options.ExecutablePath = "C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe";
                options.Headless = false;
                var browser = await playwright.Chromium.LaunchPersistentContextAsync("D:\\opt\\1", options);
                 var page = await browser.NewPageAsync();
                await page.AddInitScriptAsync("setInterval(function() {window.location.reload(true);}, 1000); ");
                //4M javascript file
                _= page.GotoAsync(Directory.GetCurrentDirectory()+"\\test.js");
            }
            catch (Exception ee) {
                Console.WriteLine(ee);
            }
             
        }
    }
}

**Steps**
- [Run the test]

**Expected**

Normal operation for 24 hours

**Actual**

Memory Leak a monent

**Comment by mxschmitt** [comment] 2024-02-13 11:11
This seems a fairly uncommon use-case - what are you trying to achieve?

For me, when I was opening the `test.js` in normal Chrome, and reloading the page manually after the site has fully loaded, and did that for 20 times, it also gained around 2,5GB of RAM.

**Comment by bba2022** [comment] 2024-02-16 12:45
> This seems a fairly uncommon use-case - what are you trying to achieve?
> 
> For me, when I was opening the `test.js` in normal Chrome, and reloading the page manually after the site has fully loaded, and did that for 20 times, it also gained around 2,5GB of RAM.

Thank you very much for your reply. This use case is indeed unrelated to playwright, and manual refreshing in regular browsers can also have the same problem. Actually, I suggest limiting the memory size of each content, as some websites may experience a memory surge after running for a long time (more than 12 hours), which can cause the software's main process to crash. The above-mentioned memory restriction function is also implemented in cefsharp, you can refer to it. Thank you very much.

**Comment by mxschmitt** [comment] 2024-02-26 20:57
I'll close this for now since this is not actionable for us. We unfortunately can't run scripts for more than 12 hours. Also testing the `file://` scheme is outside of what we support (we only support http/https). I recommend filing a new issue with an end-to-end specific testing use-case and clear reproduction steps. Thanks!

**Closed by mxschmitt** 2024-02-26 20:57 UTC
Labels: triaging
