### ISSUE TITLE
[BUG] Chrome zombie process

### ISSUE THREAD

**Issue by Saibamen** [microsoft/playwright-dotnet#2573] opened 2023-05-05 15:42 UTC
**Context:**
- Playwright Version: v1.32.0 and v1.33.0-focal
- Operating System: Linux - Docker
- .NET version: .NET 6
- Browser: Chromium

**Code Snippet**

Docker image: `mcr.microsoft.com/playwright:v1.33.0-focal` (on `playwright:v1.33.0` I have `The folder [/usr/share/dotnet/host/fxr] does not exist` error)

```cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Playwright;

namespace MyReports.Controllers
{
    [Route("api/[controller]")]
    [AllowAnonymous]
    [ApiController]
    public class VersionController : ControllerBase
    {
        public async Task<IActionResult> Index()
        {
            using var playwright = await Playwright.CreateAsync();
            await using var browser = await playwright.Chromium.LaunchAsync();

            await browser.CloseAsync();
            await browser.DisposeAsync();

            return Ok();
        }
    }
}

```

### Full repro repository: https://github.com/Saibamen/Playwright_Chrome_zombie_repro

**Describe the bug**

After every call to `/api/version` we will have +2 in zombie processes. I needed to restart container after 3 days, because there was no free memory left.

This same bug was on `v1.32.0-focal`

Related: https://github.com/microsoft/playwright-dotnet/pull/1864

**Comment by mxschmitt** [comment] 2023-05-06 08:30
Can you provide us a full reproducible which we can run locally to see this unexpected behaviour? Preferable something we can run with a single file, or inside a small Docker container.

Without that we are not able to act on it, thanks for your understanding!

**Comment by Saibamen** [comment] 2023-05-06 13:26
@mxschmitt: https://github.com/Saibamen/Playwright_Chrome_zombie_repro

**Comment by mxschmitt** [comment] 2023-05-06 21:40
Note to myself: This needs to be run on e.g. a GitHub Codespac since macOS M1 will end up building it with arm64 mode and aspnet is not available there.

I can confirm 2 zombie processes after each launch:

<img width="1350" alt="image" src="https://user-images.githubusercontent.com/17984549/236647610-3816fe12-527b-4827-9223-73200be1f1ee.png">

As a workaround you can start your Docker container using `--init` while I'm researching this more.

**Comment by Saibamen** [comment] 2023-05-07 10:19
I noticed another bug - in your screenshot, chrome process has duplicated argument:
![image](https://user-images.githubusercontent.com/905878/236671632-6823bf90-b4cc-4a94-a4f4-68ee8017002d.png)

**Comment by mxschmitt** [comment] 2023-05-09 07:08
So we don't support scenarios where no init manager is in place, since this will yield zombie processes. An init manager is essential when you want to run more complex scenarios inside Docker, [see here why you need it](https://github.com/Yelp/dumb-init#why-you-need-an-init-system).

Regarding passing `--headless` twice to Chrome, thats not us, thats what Chromium is doing internally to launch their multi process architecture. TL;DR: They spawn a sub process and pass --headless twice there. I recommend filing it at crbug.com.

<img width="1285" alt="image" src="https://user-images.githubusercontent.com/17984549/237019880-bdd8bc45-4d1d-49c5-b0ef-ee6763561e56.png">

Closing as per above, since with `--init` its working as expected.

**Closed by mxschmitt** 2023-05-09 07:08 UTC
Labels: triaging
