### ISSUE TITLE
[Question] How to import an SSL certificate?

### ISSUE THREAD

**Issue by Xen0byte** [microsoft/playwright-dotnet#1601] opened 2021-07-02 14:09 UTC
Hi! I'm targeting a host that requires SSL certificate validation, so I've installed the certificate on the machine that I'm running the tests from, and that works just fine in headed mode, however, in headless mode, I am unable to connect to the host (using Chromium, for this particular implementation). I've extracted the CRT and KEY files and attempted to import them programmatically, but I've reached a bit of a roadblock and I'm not entirely sure how to feed these to the browser context. Any suggestions that might point me in the right direction, please?

**Comment by mxschmitt** [comment] 2021-07-05 09:05
This sounds like a duplicate of https://github.com/microsoft/playwright/issues/1799 to me.

**Comment by Xen0byte** [comment] 2021-07-05 10:02
> 
> 
> This sounds like a duplicate of [microsoft/playwright#1799](https://github.com/microsoft/playwright/issues/1799) to me.

Hi @mxschmitt. As far as I can tell, and please correct me if I'm wrong, the referenced issue seems to me to be slightly different from this one, in the sense that it seems to refer to the popup that you get for selecting a certificate, which I've already worked out by creating a registry entry for the browsers I'm using.

e.g.
```
[HKEY_CURRENT_USER\SOFTWARE\Policies\Chromium\AutoSelectCertificateForUrls]
"1"="{\"pattern\":\"https://example.net/\",\"filter\":{\"ISSUER\":{\"CN\":\"CERT-NAME\"}}}"
```

Don't get me wrong, having the ability to do this programmatically without having to resort to registry hacks would be amazing, but this particular issue is not a blocker for my organization, whereas not being able to import a certificate currently is.

That being said, the answer seems to be more related to the issue I'm having so I will try to port that solution to C# code hoping it's a straightforward port. The implementation of a feature to support this at the API level would be really nice, though.

Thank you very much for the help, Max, I hope the solution from your referenced issue gets me back on track.

**Comment by Xen0byte** [comment] 2021-07-05 11:57
Hi @mxschmitt, unfortunately I've hit a roadblock again, as I am unable to find an equivalent for...

```
agentOptions: {
    ca: fs.readFileSync('./certs/ca.pem'),
    pfx: fs.readFileSync('./certs/user_cert.p12'),
    passphrase: fs.readFileSync('./certs/user_cert.p12.pwd'),
}
```

...which I assume would need to be part of a `RouteContinueOptions` object passed as the argument to a `ContinueAsync(options)` call, or maybe set an IRequest property?

Any help you could provide with this issue would be greatly appreciated, as I've invested a significant amount of time and staff resources on this particular automation project and this issue is completely blocking us from going live at the moment.

**Comment by avodovnik** [comment] 2021-07-08 07:51
If I understand your issue correctly, this  _is_ related to https://github.com/microsoft/playwright/issues/1799. I suggest that you upvote that issue so that we have an effective way of gauging interest.

As a workaround, can you try having the user certificate imported on the OS level?

**Comment by Xen0byte** [comment] 2021-07-08 08:01
Brilliant, thank you very much, I've upvoted the related issue and I'll give this snippet a try!

**Comment by avodovnik** [comment] 2021-07-08 13:46
Just to clarify one thing, did you make sure you're importing to the right cert store? I *think* `My` is correct, but I'm not 100% sure at the moment.

**Comment by Xen0byte** [comment] 2021-07-08 15:02
Hi @avodovnik. Yeah, I've tried all permutations of StoreName and StoreLocation. When I do it manually I normally import the certificate in the Personal store for the Current User.

**Comment by mxschmitt** [comment] 2021-08-24 09:02
Closing since we track this feature request upstream.

**Closed by mxschmitt** 2021-08-24 09:02 UTC
Labels: P3-collecting-feedback

**Comment by Xen0byte** [comment] 2023-05-04 08:48
There doesn't seem to be any progress on https://github.com/microsoft/playwright-dotnet/issues/1601 yet.
