### ISSUE TITLE
[BUG] Stack inspection done by playwright is fragile and breaks with Dynamic PGO enabled

### ISSUE THREAD

**Issue by AndyAyersMS** [microsoft/playwright-dotnet#2617] opened 2023-06-16 20:18 UTC
**Context:**

We enabled DynamicPGO in .NET 8 Preview 5 and are seeing reports of some failures in applications that use playwright.

See for instance https://github.com/dotnet/runtime/issues/87628

This should readily repro if you run release mode builds with .NET 8 Preview 5 and default runtime options.

**Describe the bug**

https://github.com/microsoft/playwright-dotnet/blob/ca7b02ac910e573666f48d502bfabb1c17639e68/src/Playwright/Transport/Connection.cs#L477-L502

is looking for a specific pattern of method names in the stack trace. This is fragile unless all the methods being looked for are marked with `[MethodImpl(MethodImplOptions.NoInlining)]`. Note that with PGO the JIT may now inline methods at virtual, interface, and delegate call sites.

I suspect the fix may be as simple as marking this method noinline

https://github.com/microsoft/playwright-dotnet/blob/ca7b02ac910e573666f48d502bfabb1c17639e68/src/Playwright/Transport/Connection.cs#L521-L528

but there may be more cases elsewhere in this code that need similar treatment.

**Comment by slang25** [comment] 2023-06-16 23:02
It looks like `WrapApiBoundaryAsync` might need marking as `NoInlining` too as it's searched for in the stack trace

**Comment by davidfowl** [comment] 2023-06-17 03:41
Why is this code looking at the call stack?

**Comment by slang25** [comment] 2023-06-17 10:00
Playwright has a tracing feature that's frankly amazing (see https://stu.dev/pw). It captures the API that was called by the users code, and optionally you can [include sources](https://playwright.dev/dotnet/docs/api/class-tracing#tracing-start-option-sources), this works by walking the stack frames here and only passing to playwright (the node implementation) the users stack frames.
<img width="484" alt="image" src="https://github.com/microsoft/playwright-dotnet/assets/1341446/a73166ac-5721-40f3-86db-ea5886dcb20e">

Stack frame walking is so brittle (we did it in Shouldly and I hate it), `[CallerMemberName]` might be a good solution to capture the API name, but don't think there's any alternative for the include sources functionality. This stuff probably does play well with deterministic builds either I suspect, as it's unlikely to be able to find the source files.

**Comment by mxschmitt** [comment] 2023-06-17 14:20
Thanks for the investigation! The internal stack collection gets used for various things, e.g. as per above trace viewer where the actual .NET API calls get shown or we use it internally for logging (to know which .NET API calls (which are exposed) belong to which internal protocol API call).

I tried to reproduce it using https://github.com/dotnet/runtime/issues/87628#issuecomment-1594486535 and our [official getting started](https://playwright.dev/dotnet/docs/library) on .NET 8 preview 5 (8.0.100-preview.5.23303.2) but was in both cases unfortunately not able to. I'm on macOS, as per the issue in the runtime repo, it was also reproducible there.

**Comment by AndyAyersMS** [comment] 2023-06-20 03:05
> I tried to reproduce it using [dotnet/runtime#87628 (comment)](https://github.com/dotnet/runtime/issues/87628#issuecomment-1594486535) and our [official getting started](https://playwright.dev/dotnet/docs/library) on .NET 8 preview 5 (8.0.100-preview.5.23303.2) but was in both cases unfortunately not able to. I'm on macOS, as per the issue in the runtime repo, it was also reproducible there.
> 
> What did you do differently? I made sure its a Release build.

So you ran with `dotnet run -c Release`>

You may need to run enough code to get things to properly tier up (eg repeatedly call things in a loop, 100x or so should do the trick). You can set `DOTNET_JitDisasmSummary=1` in the environment where you launch dotnet, and see how many methods report being optimized with Dynamic PGO.

**Comment by AndyAyersMS** [comment] 2023-06-20 20:38
I can repro if I update the getting started example to:
```C#
using Microsoft.Playwright;

using var playwright = await Playwright.CreateAsync();

for (int i = 0; i < 100; i++)
{
await using var browser = await playwright.Chromium.LaunchAsync();
var page = await browser.NewPageAsync();
await page.GotoAsync("https://playwright.dev/dotnet");
await page.ScreenshotAsync(new()
{
    Path = "screenshot.png"
});
}
```
for example
```
C:\bugs\playwright>dotnet build -c Release
MSBuild version 17.7.0-preview-23281-03+4ce2ff1f8 for .NET
  Determining projects to restore...
  All projects are up-to-date for restore.
C:\Program Files\dotnet\sdk\8.0.100-preview.5.23303.2\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.RuntimeIdentifierInference.targets(314,5): message NETSDK1057: You are usi
ng a preview version of .NET. See: https://aka.ms/dotnet-support-policy [C:\bugs\playwright\playwright.csproj]
  playwright -> C:\bugs\playwright\bin\Release\net8.0\playwright.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:01.07

C:\bugs\playwright>dotnet exec C:\bugs\playwright\bin\Release\net8.0\playwright.dll
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Playwright.Transport.Connection.InnerSendMessageToServerAsync[T](String guid, String method, Dictionary`2 dictionary, Boolean keepNulls) in /_/src/Playwright/Transport/Connection.cs:line 150
   at Microsoft.Playwright.Transport.Connection.WrapApiCallAsync[T](Func`1 action, Boolean isInternal)
   at Microsoft.Playwright.Core.BrowserType.LaunchAsync(BrowserTypeLaunchOptions options) in /_/src/Playwright/Core/BrowserType.cs:line 61
   at Program.<Main>$(String[] args) in C:\bugs\playwright\Program.cs:line 7
   at Program.<Main>(String[] args)
```
I'll try this on my M1 and see if the same thing happens there.

**Comment by AndyAyersMS** [comment] 2023-06-20 23:24
I can also repro this on the M1 with .Net 8 Preview 5.

**Closed** 2023-06-26 21:08 UTC
Labels: triaging

**Comment by AndyAyersMS** [comment] 2023-06-29 02:29
Any idea when this fix might appear in a release? A couple other partner teams are running into this.

**Comment by mxschmitt** [comment] 2023-06-29 05:42
> Any idea when this fix might appear in a release? A couple other partner teams are running into this.

Probably in 2-3 weeks.

**Comment by timmydo** [comment] 2023-06-29 16:51
@AndyAyersMS I don't think we will be able to ship on preview 5 then.

**Comment by AndyAyersMS** [comment] 2023-06-29 17:03
@mxschmitt would it be possible to create a release sooner? I would like to be able to unblock @timmydo if possible.

**Comment by martincostello** [comment] 2023-06-30 12:15
Just to confirm, all of the repos where I originally hit this issue are all working correctly with PGO enabled using the above beta package.
