### ISSUE TITLE
[Question]: I can not got iframe 's body.

### ISSUE THREAD

**Issue by interiv** [microsoft/playwright-dotnet#1610] opened 2021-07-11 14:14 UTC
### Your question

```
public async Task a()
{
    var playwright = await Microsoft.Playwright.Playwright.CreateAsync();

    var browser = await playwright.Chromium.LaunchAsync(new BrowserTypeLaunchOptions()
    {
        Headless = false,
        Channel = "msedge-canary",
        SlowMo = 50,
    });
    var context2 = await browser.NewContextAsync();
    var p = await context2.NewPageAsync();

    await p.GotoAsync("d:\\a.html");
    try
    {
       var iframe = await p.QuerySelectorAsync("#ueditor_0");
        var contentFrame = await iframe.ContentFrameAsync();
        var bbb = await contentFrame.QuerySelectorAllAsync("body");
    }
    catch (Exception ex)
    {
        MessageBox.Show("ex"+ex.Message);
    }
    MessageBox.Show("over");
}

```
a.html file is here

https<span>://ws28.cn</span>/f/5vp0fywh31h

**Comment by interiv** [comment] 2021-07-11 14:15
`<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<p>there has a frame</p>
<iframe id="ueditor_0" width="100%" height="100%" frameborder="0"
        src="javascript:void(function(){document.open();
        document.write(&quot;<!DOCTYPE html>
        <html xmlns='http://www.w3.org/1999/xhtml' class='view' >
        <head><style type='text/css'>.view{padding:0;word-wrap:break-word;cursor:text;height:90%;}
body{margin:8px;font-family:sans-serif;font-size:16px;}p{margin:5px 0;}</style></head>
<body class='view' ><p>111111111111</p></body>
<script type='text/javascript'  id='_initialScript'>
setTimeout(function(){editor = window.parent.UE.instants['ueditorInstant0'];editor._setup(document);},0);
var _tmpScript = document.getElementById('_initialScript');
_tmpScript.parentNode.removeChild(_tmpScript);</script>
</html>&quot;);document.close();}())"></iframe>
</body>
</html>
`

**Comment by interiv** [comment] 2021-07-11 14:18
a file  is here

https://ws28.cn/f/5voz8lvw1b9 复制链接到浏览器打开

**Comment by avodovnik** [comment] 2021-07-12 17:50
This seems to be related/duplicate of https://github.com/microsoft/playwright/issues/7556

**Comment by interiv** [comment] 2021-07-12 23:53
not only.net has this problem，other like js has this problem too

**Comment by avodovnik** [comment] 2021-07-13 07:10
Yes, since Playwright for .NET is a _client_ for Playwright, a bug/issue/feature that appears in upstream, will surface in all of the languages. I'm closing this issue on our side. 

It's currently marked as P3 on the upstream side, and when it gets fixed, it will be fixed in .NET as well.

**Closed by avodovnik** 2021-07-13 07:10 UTC
Labels: triaging
