### ISSUE TITLE
[Feature]: Chrome Devtools Protocol

### ISSUE THREAD

**Issue by mikesisti** [microsoft/playwright-dotnet#1735] opened 2021-09-08 18:17 UTC
### Feature request

Hi Microsoft- are there plans to add this feature in the future?

https://playwright.dev/dotnet/docs/api/class-browsercontext

Thanks in advance

**Comment by avodovnik** [comment] 2021-09-09 07:31
Do you mean .NET support for https://playwright.dev/docs/api/class-cdpsession ?

**Comment by avodovnik** [comment] 2021-09-09 07:38
Looks like a duplicate of #1291, closing in favour of that one. 

If this isn't a duplicate, please provide more clarity on what the request is for, and we'll be happy to revisit and/or reopen.

**Closed by avodovnik** 2021-09-09 07:38 UTC
Labels: triaging
