### ISSUE TITLE
[Question]: What's the best thing to do if I want to synchronize operations between multiple browsers?

### ISSUE THREAD

**Issue by bbhxwl** [microsoft/playwright-dotnet#1902] opened 2021-12-20 14:04 UTC
### Your question

I want to access browser A. For example, I enter my account password and log in. My other browsers B and C all repeat the operations of my browser A. what should I do?

**Comment by mxschmitt** [comment] 2021-12-20 15:19
Closing as duplicate of https://github.com/microsoft/playwright/issues/11023

**Closed** 2021-12-20 15:19 UTC
