### ISSUE TITLE
How do I install Playwright in an existing project?

### ISSUE THREAD

**Issue by ftpguy** [microsoft/playwright-dotnet#1608] opened 2021-07-11 00:09 UTC
### Playwright version

1.12.2

### Operating system

Windows

### What browsers are you seeing the problem on?

Chromium

### Other information

.NET framework 4.8
VS 2019
Windows 7
Console app
Microsoft.Playwright 1.12.2
Microsoft.Playwright.CLI 1.0.0

### What happened? / Describe the bug

I am trying to use the code that I copied/pasted from here:

https://playwright.dev/dotnet/docs/intro/#first-project

On `Playwright.CreateAsync()`, it throws the following exception:

    Microsoft.Playwright.PlaywrightException: 'Driver not found: F:\Users\username\Documents\Visual Studio 
    Projects\projectname\projectname\bin\Debug\.playwright\node\win32_x64\playwright.cmd'`

I ran `dotnet tool install --global Microsoft.Playwright.CLI` in package manage console and nothing happened the first time. When I ran it again, it said _Tool 'microsoft.playwright.cli' is already installed_, so I assume it actually _did_ do something the first time. Still, I got the same exception. I then ran `playwright install` to see if it would do anything and I got this exception:

	playwright.exe : Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Bcl.AsyncInterfaces, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
	At line:1 char:11
	+ playwright <<<<  install
		+ CategoryInfo          : NotSpecified: (Unhandled excep...file specified.:String) [], RemoteException
		+ FullyQualifiedErrorId : NativeCommandError
	 
	File name: 'Microsoft.Bcl.AsyncInterfaces, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
	   at System.Reflection.RuntimeAssembly.GetExportedTypes()
	   at Microsoft.Playwright.CLI.Program.Main(String[] args) in /_/src/Playwright.CLI/Program.cs:line 53

No idea what to do. I've only ever had success when installing packages from NuGet, but this one seems to be giving me trouble.

### Code snippet to reproduce your bug

```shell
public static async Task Start()
    {
        using var playwright = await Playwright.CreateAsync();
        await using var browser = await playwright.Chromium.LaunchAsync();
        var page = await browser.NewPageAsync();
        await page.GotoAsync("https://playwright.dev/dotnet");
        await page.ScreenshotAsync(new PageScreenshotOptions { Path = "screenshot.png" });
    }
```

**Comment by ftpguy** [comment] 2021-07-11 03:20
In my OP, I was trying to get PlayWright working in an existing project. This time, I followed the exact directions in the link provided in my OP and I was able to run my code without issues. _However_, I would not call this resolved because I need to know what I have to do to incorporate this into an existing project.

**Comment by avodovnik** [comment] 2021-07-13 17:18
@ftpguy do you have anything set in your `PLAYWRIGHT_BROWSERS_PATH` by any chance?

**Comment by avodovnik** [comment] 2021-07-19 12:10
I'm closing this for now, since there's no reply, but feel free to ping us if the issue is not resolved, and I'm happy to reopen it.

**Closed by avodovnik** 2021-07-19 12:10 UTC
Labels: triaging
