### ISSUE TITLE
[BUG] Failed to load extension (.NET)

### ISSUE THREAD

**Issue by salvadorjhai** [microsoft/playwright-dotnet#2442] opened 2023-01-05 09:24 UTC
does loading extension still work?

because **it seems that its prefixing google chrome path from the actual extension path which makes it fail.**

Im getting this error when launching playwright.
```
---------------------------
Error Loading Extension
---------------------------
Failed to load extension from: C:\Program Files (x86)\Google\Chrome\Application\108.0.5359.125\"D:\Projects\.NET Shared Codes\scraptest2playwrite\scraptest2playwrite\bin\Debug\chrome-extensions\ublock-origin-lite-chrome". Manifest file is missing or unreadable
---------------------------
OK   
---------------------------
```

its prefixing chrome path **C:\Program Files (x86)\Google\Chrome\Application\108.0.5359.125\** from my actual extension path.

heres the command line i used in loading;
```
--disable-extensions-except="D:\Projects\.NET Shared Codes\scraptest2playwrite\scraptest2playwrite\bin\Debug\chrome-extensions\ublock-origin-lite-chrome" 
--load-extension="D:\Projects\.NET Shared Codes\scraptest2playwrite\scraptest2playwrite\bin\Debug\chrome-extensions\ublock-origin-lite-chrome" 
```

```
' lstArgs here contains the command line above;

        Dim config As New BrowserTypeLaunchPersistentContextOptions
        With config
            .Channel = "chrome"
            .Locale = "en-US"
            .Headless = False
            .Devtools = True
            .DownloadsPath = Path.GetFullPath(".\chrome-downloads")
            .Args = lstArgs
            .IgnoreDefaultArgs = {"--disable-extensions"}
            .JavaScriptEnabled = True
        End With
        
        Dim PL = Playwright.CreateAsync().Result
        Dim browser = PL.Chromium.LaunchPersistentContextAsync(Path.GetFullPath(".\chrome-data"), config).Result

```

Im using .net 4.6.1, and 1.28.0 version of playwright nugget, 

anyone?

**Comment by mxschmitt** [comment] 2023-01-05 09:36
Yes it should work, did you see the error? `Manifest file is missing or unreadable`

**Comment by salvadorjhai** [comment] 2023-01-05 10:16
> Yes it should work, did you see the error? `Manifest file is missing or unreadable`

yes. i can see the error thats why i posted it. 

you can also see it was showing an additional path from the extension which i did not even set. 

and yes, manifest file exist and extension path i set is true and correct.

**Comment by mxschmitt** [comment] 2023-01-16 10:52
Looks like its caused by the quotes which are used and that your path contains spaces. I recommend to use single quotes or no quotes at all, then it should work.

Closing since this is more a Chromium related issue rather than Playwright.

**Closed by mxschmitt** 2023-01-16 10:52 UTC

**Comment by salvadorjhai** [comment] 2023-01-16 12:30
> 

**i dont think this is an issue with chromium** since im using the same extension path and same argument list when using puppeteer and it works using installed google chrome or using a vanilla chromium.

even the provided sample from this full repo causes the same error if extension path is added.

```
using Microsoft.Playwright;

using var playwright = await Playwright.CreateAsync();

// Failed to load extension from: C:\Program Files(x86)\Google\Chrome\Application\109.0.5414.74\ ...... Manifest file is missing or unreadable
string[] lstArgs = { @"--disable-extensions-except=""D:\Projects\.NET Shared Codes\scraptest2playwrite\scraptest2playwrite\bin\Debug\chrome-extensions\ublock-origin-lite-chrome""",
@"--load-extension=""D:\Projects\.NET Shared Codes\scraptest2playwrite\scraptest2playwrite\bin\Debug\chrome-extensions\ublock-origin-lite-chrome"""};

// Failed to load extension from: C:\Program Files(x86)\Google\Chrome\Application\109.0.5414.74\ ...... Manifest file is missing or unreadable
//string[] lstArgs = { @"--disable-extensions-except='D:\Projects\.NET Shared Codes\scraptest2playwrite\scraptest2playwrite\bin\Debug\chrome-extensions\ublock-origin-lite-chrome'",
//@"--load-extension='D:\Projects\.NET Shared Codes\scraptest2playwrite\scraptest2playwrite\bin\Debug\chrome-extensions\ublock-origin-lite-chrome'"};

// will error and will not work because path needs to be inside a single or double quote
//string[] lstArgs = { @"--disable-extensions-except=D:\Projects\.NET Shared Codes\scraptest2playwrite\scraptest2playwrite\bin\Debug\chrome-extensions\ublock-origin-lite-chrome",
//@"--load-extension=D:\Projects\.NET Shared Codes\scraptest2playwrite\scraptest2playwrite\bin\Debug\chrome-extensions\ublock-origin-lite-chrome"};

// even if you put your extension folder on drive c: (testing with single/double quote)
// Failed to load extension from: C:\Program Files(x86)\Google\Chrome\Application\109.0.5414.74\"C:\chrome-extensions\ublock-origin-lite-chrome".Manifest file is missing or unreadable
//string[] lstArgs = { @"--disable-extensions-except=""C:\chrome-extensions\ublock-origin-lite-chrome""",
//@"--load-extension=""C:\chrome-extensions\ublock-origin-lite-chrome"""};

string[] ignoreArgs = { "--disable-extensions", "--enable-automation" };

await using var browser = await playwright.Chromium.LaunchPersistentContextAsync(Path.GetFullPath($".\\chrome-data-dir"),
    new BrowserTypeLaunchPersistentContextOptions() {  Channel = "chrome", Headless = false,
        IgnoreDefaultArgs = ignoreArgs, Args = lstArgs, ExecutablePath = @"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" });

var page = await browser.NewPageAsync();
await page.GotoAsync("https://playwright.dev/dotnet");
await page.ScreenshotAsync(new PageScreenshotOptions { Path = "screenshot.png" });

```

**Comment by mxschmitt** [comment] 2023-01-16 12:42
The following works for me, it contains spaces and brackets:

```csharp

using Microsoft.Playwright;

using var playwright = await Playwright.CreateAsync();
var extensionPath = "C:\\Users\\maxschmitt\\development\\playwright-dotnet\\src\\Playwright.Tests.TestServer\\assets\\simple-extension (81)";
await using var context = await playwright.Chromium.LaunchPersistentContextAsync("", new(){
    Headless = false,
    Args = new[] {
        $"--disable-extensions-except={extensionPath}",
        $"--load-extension={extensionPath}"
    },
});
await context.Pages[0].PauseAsync();
```

Looks like in your case the issue is that you did not escape the slashes.

**Comment by salvadorjhai** [comment] 2023-01-16 13:01
> The following works for me, it contains spaces and brackets:
> 
> ```cs
> using Microsoft.Playwright;
> 
> using var playwright = await Playwright.CreateAsync();
> var extensionPath = "C:\\Users\\maxschmitt\\development\\playwright-dotnet\\src\\Playwright.Tests.TestServer\\assets\\simple-extension (81)";
> await using var context = await playwright.Chromium.LaunchPersistentContextAsync("", new(){
>     Headless = false,
>     Args = new[] {
>         $"--disable-extensions-except={extensionPath}",
>         $"--load-extension={extensionPath}"
>     },
> });
> await context.Pages[0].PauseAsync();
> ```
> 
> Looks like in your case the issue is that you did not escape the slashes.

FINALLY it works.. lol
case solved. thanks...
