### ISSUE TITLE
[BUG] SetInputFilesAsync() allocates extremely large amount of memory

### ISSUE THREAD

**Issue by kelmelzer** [microsoft/playwright-dotnet#2629] opened 2023-07-05 18:52 UTC
**Context:**
- Playwright Version: 1.35
- Operating System: Windows
- .NET version: .NET 6 and .NET 7
- Browser: Chromium, Firefox, Webkit
- Extra: Also occurs with Selenium Grid integration (using environment variable)

**Code Snippet**

```cs
[TestFixture]
public class PlaywrightPOCTest
{
    private static IPlaywright playwright;
    private static IBrowser browser;
    private static IBrowserContext context;
    private static IPage page;

    [OneTimeSetUp]
    public static async Task DownloadBrowsers()
    {
        var exitCode = Microsoft.Playwright.Program.Main(new[] { "install" });
        if (exitCode != 0)
        {
            throw new Exception($"Playwright exited with code {exitCode}");
        }

        playwright = await Playwright.CreateAsync();
    }

    [OneTimeSetUp]
    public static async Task EdgeDriverInitialize()
    {
        browser = await playwright.Chromium.LaunchAsync(
            new BrowserTypeLaunchOptions 
            { Channel = "msedge", Headless = true, /*SlowMo = 2000 */}
            );

        context = await browser.NewContextAsync(); 

        page = await context.NewPageAsync();
    }

    [Test]
    public static async Task PlaywrightFileUpload()
    {
        var frame = page.MainFrame;

        await frame.GotoAsync(@"http://www.fileconvoy.com/");
        Console.WriteLine($"Memory usage before upload: {System.Diagnostics.Process.GetCurrentProcess().PrivateMemorySize64}");
        await frame.Locator("id=upfile_0").SetInputFilesAsync(@"C:\Users\testuser\Downloads\19588.pdf");
        Console.WriteLine($"Memory usage after upload: {System.Diagnostics.Process.GetCurrentProcess().PrivateMemorySize64}");
        await frame.Locator("id=readTermsOfUse").CheckAsync();
        await frame.GetByRole(AriaRole.Button).GetByText("Upload").ClickAsync();
        Console.WriteLine($"Memory usage after page navigation: {System.Diagnostics.Process.GetCurrentProcess().PrivateMemorySize64}");
    }

    [OneTimeTearDown]
    public static async Task EdgeDriverCleanup()
    {
        await context?.CloseAsync();
        await browser?.CloseAsync();
        playwright.Dispose();
    }
}
```

**Describe the bug**

Steps

-Download this ~30MB PDF from here: https://research.nhm.org/pdfs/19588/19588.pdf
-Update path in SetInputFilesAsync() method to your file location
-Run PlaywrightFileUpload() test

Expected Results:

I would expect memory usage to increase temporarily by the uploaded filesize (~30MB) and then go away or be cleaned up fairly soon after page navigation occurs.

Actual Results:

Memory usage jumps from about 40MB to >700MB just from the file upload and persists for quite a long time in other tests which do not involve file uploads. Sometimes I can get it to drop by forcing a GC using GC.Collect() several minutes later, but I definitely should not be doing that.

This has had an impact on long running scenarios where we are doing a file upload as the first dependency and then running several tests on a web app after the upload. It also affects concurrent runs in our framework due to out of memory issues. Fwiw, I took a memory snapshot inside VS, and it shows up as a large number of dead char[] objects which are outside of my code.

**Comment by kelmelzer** [comment] 2023-07-10 00:23
An update after more code research...

If I use a PDF that is above the 50MB filesize limit like with a 60MB PDF, it skips saving a base64 copy to a buffer which is where the memory leak occurs. I have tested the >50MB limit with both codepaths, local and remote (Selenium Grid), and the memory  issue did not occur as well as being faster since it skips the byte[] conversion to base64. Memory jumped to 55MB around the upload and moved back to ~35MB after ClickAsync() to navigate/submit the form.

Was there a reason for this 50MB limit? Maybe it makes since more around 1 or 2MB?

**Comment by mxschmitt** [comment] 2023-07-10 06:07
I was able to reproduce. Memory went up to 2 GB for me

**Comment by mxschmitt** [comment] 2023-10-23 20:52
Closing for now and waiting for more user reports! Since on macOS it seems fine and Node.js seems to collect memory after a few seconds.

**Closed by mxschmitt** 2023-10-23 20:52 UTC
Labels: v1.40
