### ISSUE TITLE
+ Reference in the manifest does not match the identity of the downloaded assembly Microsoft.Playwright.dll.

### ISSUE THREAD

**Issue by ahmwai** [microsoft/playwright-dotnet#2087] opened 2022-04-07 07:09 UTC
**Context:**
- Playwright Version: [what Playwright version do you use?]
- Operating System: Windows 10
- .NET version: 4.8
- Browser: Chromium
- Extra: [any specific details about your environment]

Hello team,

We have problem after we made publish for the windows app, and we tried to setup the instaltion we are getting this error :

+ Reference in the manifest does not match the identity of the downloaded assembly Microsoft.Playwright.dll.

RROR DETAILS
	Following errors were detected during this operation.
	* [4/7/2022 2:59:04 PM] System.Deployment.Application.InvalidDeploymentException (RefDefValidation)
		- Reference in the manifest does not match the identity of the downloaded assembly Microsoft.Playwright.dll.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.DownloadManager.ProcessDownloadedFile(Object sender, DownloadEventArgs e)
			at System.Deployment.Application.FileDownloader.DownloadModifiedEventHandler.Invoke(Object sender, DownloadEventArgs e)
			at System.Deployment.Application.FileDownloader.OnModified()
			at System.Deployment.Application.SystemNetDownloader.DownloadSingleFile(DownloadQueueItem next)
			at System.Deployment.Application.SystemNetDownloader.DownloadAllFiles()
			at System.Deployment.Application.FileDownloader.Download(SubscriptionState subState, X509Certificate2 clientCertificate)
			at System.Deployment.Application.DownloadManager.DownloadDependencies(SubscriptionState subState, AssemblyManifest deployManifest, AssemblyManifest appManifest, Uri sourceUriBase, String targetDirectory, String group, IDownloadNotification notification, DownloadOptions options)
			at System.Deployment.Application.ApplicationActivator.DownloadApplication(SubscriptionState subState, ActivationDescription actDesc, Int64 transactionId, TempDirectory& downloadTemp)
			at System.Deployment.Application.ApplicationActivator.InstallApplication(SubscriptionState& subState, ActivationDescription actDesc)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl, Uri& deploymentUri)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
--- End of stack trace from previous location where exception was thrown ---
			at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)

COMPONENT STORE TRANSACTION DETAILS
	No transaction information is available.
	
	
	kindly let us know what is the issue and how to solve it

**Comment by freesiafreesia** [comment] 2022-07-26 05:04
I had the same error before.
In my case, the cause was the version of System.Text.Json.dll didn't match between Playwright and my app.
While Playwright uses the latest version of System.Text.Json.dll but mine used 6.0.0.1.
After using the latest version of System.Text.Json.dll (currently 6.0.0.5), the error has gone.
Don't forget to include "YourApp.exe.config" file with YourApp.exe and make sure it has the following lines.

> 

      <dependentAssembly>
        <assemblyIdentity name="System.Text.Json" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-6.0.0.5" newVersion="6.0.0.5" />
      </dependentAssembly>

**Comment by mxschmitt** [comment] 2022-07-26 07:07
Closing since it seems fixed and we upgraded the json dependency

**Closed by mxschmitt** 2022-07-26 07:07 UTC
