### ISSUE TITLE
[Bug]: NullReferenceException thrown when calling BrowserTearDown

### ISSUE THREAD

**Issue by terius7** [microsoft/playwright-dotnet#2958] opened 2024-07-11 11:33 UTC
### Version

1.44.0

### Steps to reproduce

All tests are failing due to TestCleanup error.

### Expected behavior

TestOK property correctly returns true or false and tests are passing., and tests pass

### Actual behavior

Message: TestCleanup method XXX.BrowserTearDown threw an exception. System.NullReferenceException: Object reference not set to an instance of an object...

Stack Trace:
   PlaywrightTest.get_TestOK() line121
   BrowserTest.BrowserTearDown() line54

### Additional context

In the PlaywrightTest class line 125
`public TestContext TestContext { get; set; } = null!;
`

The TestContext property is not correctly set up to be automatically injected by MsTest. The initialisation to `null!` might be misleading.

**Solution:**
```
protected bool TestOK
{
   get => TestContext.CurrentTestOutcome == UnitTestOutcome.Passed || TestContext.CurrentTestOutcome == UnitTestOutcome.NotRunnable;
}

public TestContext TestContext { get; set; }
```

### Environment

```Text
- Operating System: [Windows 11]
- CPU: [arm64]
- Browser: [All]
- .NET Version (TFM): [net8.0]
- Other info:
```

**Comment by mxschmitt** [comment] 2024-07-11 23:20
Could you help us how to reproduce this issue? We have not seen this before.

**Comment by terius7** [comment] 2024-07-13 19:37
`namespace TestProject
{
    [TestClass]
    public class UnitTest1 : PageTest
    {
        [TestMethod]
        public async Task HomepageHasPlaywrightInTitleAndGetStartedLinkLinkingtoTheIntroPage()
        {
            await Page.GotoAsync("https://playwright.dev");

            // Expect a title "to contain" a substring.
            await Expect(Page).ToHaveTitleAsync(new Regex("Playwright"));

            // create a locator
            var getStarted = Page.Locator("text=Get Started");

            // Expect an attribute "to be strictly equal" to the value.
            await Expect(getStarted).ToHaveAttributeAsync("href", "/docs/intro");

            // Click the get started link.
            await getStarted.ClickAsync();

            // Expects the URL to contain intro.
            await Expect(Page).ToHaveURLAsync(new Regex(".*intro"));
        }

        public TestContext TestContext { get; set; }
    }
}
`

**Comment by mxschmitt** [comment] 2024-07-15 09:36
I see, looks like a MSTest bug to me. When `TestContext` gets overridden, then the inherited class `TestInitialize` or `TestCleanup` won't have access to it anymore:

```csharp
namespace dotnet_mstest;

public class BaseClass
{
    public TestContext TestContext { get; set; } = null!;

    [TestCleanup]
    public void BaseClassTearDown()
    {
        Console.WriteLine("BaseClassTearDown: " + TestContext.TestName);
    }
}

[TestClass]
public class UnitTest1 : BaseClass
{
    [TestMethod]
    public void MyTest()
    {
    }

    // If you comment out the following line, BaseClassTearDown works as expected.
    public TestContext TestContext { get; set; } = null!;

    [TestCleanup]
    public void UnitTest1TearDown()
    {
        Console.WriteLine("UnitTest1TearDown: " + TestContext.TestName);
    }
}
```

Expected: Passes
Actual: In `BaseClassTearDown` `TestContext` is null.

@terius7 as a workaround you can maybe not re-define `TestContext` and use ours? Since its also public.

**Comment by nohwnd** [comment] 2024-07-15 09:51
Please avoid overriding the property and it will work, and the property will be inherited to all the children.

I don't think this is a bug per-se, the code does exactly what you are asking it to, you have a property TestContext that is hiding a property on the base class, the compiler even recommends to make this explicit by using the `new` modifier on the property, to highlight that this is hiding a non-overridable member on the base class. 

I agree this is not obvious when executing tests, and the framework could work around this edge case at the expense of being a bit slower. And also not being consistent with the behavior of hiding a test method, where only the one visible on the current class is executed (the orange one in the screenshot below). 

![image](https://github.com/user-attachments/assets/bdcef2cb-5216-450a-82bb-cc738ef06394)

@evangelink do you think we should fix this in MSTest?

**Comment by Evangelink** [comment] 2024-07-15 12:03
Thanks for the analysis @nohwnd! I do agree with you that we should close this issue as MSTest is working as "intended" when you are doing shadowing. But we agree that shadowing a member in the context of testing is most of the time a bad idea and should be prevented, to this goal we will add an analyzer: https://github.com/microsoft/testfx/issues/3263.

Looking at the code in this issue, I have also noticed that it seems to be a common practice to use the `= null!` to avoid the nullability analysis, to simplify the code, I suggest to add a code suppressor on MSTest so that's not required: https://github.com/microsoft/testfx/issues/3262

**Closed** 2024-07-15 12:05 UTC
