### ISSUE TITLE
[Question]: Is there a way to attach to a existing browser

### ISSUE THREAD

**Issue by anunay1** [microsoft/playwright-dotnet#1746] opened 2021-09-15 10:05 UTC
### Your question

Hi, 

I have a scenario to automate wherein I have a word document and then I click on wikipedia, I have automated the opening of the word document and want to use playwright to automated the wikipedia part. Is there a way to attach a existing browser?

**Comment by avodovnik** [comment] 2021-09-15 15:05
Not at the moment, but it's something we're working on porting over to .NET.

Are you specifically looking for CDP or WebSocket connections?

**Comment by anunay1** [comment] 2021-09-15 15:07
Yes

**Comment by avodovnik** [comment] 2021-09-15 15:24
In that case, this is likely a duplicate of #1291

**Closed** 2021-09-28 07:06 UTC
Labels: P3-collecting-feedback
