### ISSUE TITLE
Install in VS2022 ? Help please :)

### ISSUE THREAD

**Issue by CyrilIDsoft** [microsoft/playwright-dotnet#2472] opened 2023-01-29 20:21 UTC
Hello
Playwright noob so be kind. 🙂

I installed Microsoft.Playwright 1.30.0 + Microsoft.Playwright.MSTest 1.30.0 + Microsoft.Playwright.TestAdapter 1.30.0 in my Visual Studio 2022.
Trying to run samples found (https://playwright.dev/) I have a compiling error on this sentence : 

using var playwright = await Playwright.CreateAsync();

Any idea on what I may have missed ?

Thanks.

**Comment by CyrilIDsoft** [comment] 2023-01-31 10:17
I tried in Visual Studio Code and it works ... What's the matter ?

**Comment by mxschmitt** [comment] 2023-01-31 10:18
Super weird! Maybe the dependencies were not restored in VS. Have you tried following the official intro? https://playwright.dev/dotnet/docs/intro

**Comment by CyrilIDsoft** [comment] 2023-01-31 10:34
Well in VS2022 I used the NuGet package manager to install Microsoft.Playwright.MSTest.
I also desinstall and reinstall this package to test, without improvment.

**Comment by mxschmitt** [comment] 2023-02-02 14:43
This is most likely an issue on your machine, with the way VS is installed etc. since you are the first person reporting it. Since we are unfortunately not able to reproduce it, we have to close it for now as part of the triaging process. Feel free to put research / investigation notes down below to help further users.

I'd recommend to re-install VS 2022.

**Closed by mxschmitt** 2023-02-02 14:43 UTC
Labels: triaging

**Comment by ArpitaJanaAnthology** [comment] 2023-10-17 11:26
I see the same issue ,  Playwright does not even show up in the list of extensions that Visual Studio 2022 offers for the IDE
<img width="855" alt="Screenshot 2023-10-17 165556" src="https://github.com/microsoft/playwright-dotnet/assets/147484536/34c902d2-2c60-4e2c-ac77-ab4bca076df7">

**Comment by mxschmitt** [comment] 2023-10-17 12:58
> I see the same issue , Playwright does not even show up in the list of extensions that Visual Studio 2022 offers for the IDE <img alt="Screenshot 2023-10-17 165556" width="855" src="https://user-images.githubusercontent.com/147484536/275816364-34c902d2-2c60-4e2c-ac77-ab4bca076df7.png">

This is expected, there is no Visual Studio Playwright extension, only for Visual Studio Code and Node.js: https://playwright.dev/docs/getting-started-vscode

**Comment by eggman211** [comment] 2024-07-01 15:37
I know this post is an old and closed but I just had this issue.  Found out it was because Playwright was referencing PlaywrightTest and not Microsoft.Playwright.Playwright

![image](https://github.com/microsoft/playwright-dotnet/assets/61326291/1e884985-fc6b-4007-944b-fb8489a2e6ef)

**Comment by chan1385** [comment] 2025-02-18 23:52
In your code, remove the extension to PageTest for the class file. Include an empty Setup attribute within current class file. That worked for me.
