### ISSUE TITLE
[Question] Running under impersonation - feasible?

### ISSUE THREAD

**Issue by poulhoecherl** [microsoft/playwright-dotnet#2177] opened 2022-06-14 16:04 UTC
I am trying to run Playwright test code on a CI pipeline against a Blazor app that requires WIndows authentication using  a domain test user credential. 

Here is a simplified example what I'm trying to do, using a (Win32) SafeAccessTokenHandle instance: 

```
var credentials = new UserCredentials(domain, username, password);

var userHandle = credentials.LogonUser(LogonType.Interactive);

var titleString = await WindowsIdentity.RunImpersonated(userHandle, async () =>
{

    using var playwright = await Playwright.CreateAsync();

    var browser = await playwright.Chromium.LaunchAsync(new() { Headless = true });

    var page = await browser.NewPageAsync();

    var response = await page.GotoAsync(TheAppUrl);

    return await page.TitleAsync();

});
```

If I try to run the test block impersonated as a the domain test user, I get the following exception:

```
Microsoft.Playwright.PlaywrightException
  HResult=0x80131500
  Message=System.IO.IOException: The pipe has been ended.
   at System.IO.RandomAccess.WriteAtOffset(SafeFileHandle handle, ReadOnlySpan`1 buffer, Int64 fileOffset)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.ThreadPoolValueTaskSource.ExecuteInternal()
--- End of stack trace from previous location ---
   at Microsoft.Win32.SafeHandles.SafeFileHandle.ThreadPoolValueTaskSource.GetResult(Int16 token)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.ThreadPoolValueTaskSource.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.IO.Strategies.BufferedFileStreamStrategy.WriteToNonSeekableAsync(ReadOnlyMemory`1 source, CancellationToken cancellationToken)
   at Microsoft.Playwright.Transport.StdIOTransport.SendAsync(Byte[] message) in /_/src/Playwright/Transport/StdIOTransport.cs:line 106
  Source=System.Private.CoreLib
```

It seems like the handle context might be getting lost during execution.

Perhaps there is a synchrony context that I am not understanding?

If I run the test code without Impersonation, it executes successfully.

Any thoughts/ideas/examples?

**Comment by mxschmitt** [comment] 2022-06-16 08:39
Since you are using Playwright for .NET it gets transferred to the playwright-dotnet repository.

I see this error for the first time, so its most likely some edge case. Is the code above enough to reproduce it locally?

**Comment by poulhoecherl** [comment] 2022-06-17 19:20
Much thanks for the update - I'll track it there.

Yes I have been able to repro consistently in environments using Windows Authentication.

**Comment by mxschmitt** [comment] 2022-07-08 14:50
We unfortunately don't have an environment to reproduce and the resources to dig into it. Most likely the project has no access to to the files, or the bin folder is not distributed/build or the browsers not installed.

**Closed by mxschmitt** 2022-07-08 14:50 UTC
Labels: triaging

**Comment by yash-saini** [comment] 2024-03-25 17:20
I am again getting the same error.
Microsoft.Playwright.PlaywrightException
  HResult=0x80131500
  Message=System.IO.IOException: The pipe has been ended.
   at System.IO.RandomAccess.WriteAtOffset(SafeFileHandle handle, ReadOnlySpan`1 buffer, Int64 fileOffset)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.ThreadPoolValueTaskSource.ExecuteInternal()
--- End of stack trace from previous location ---
   at Microsoft.Win32.SafeHandles.SafeFileHandle.ThreadPoolValueTaskSource.GetResult(Int16 token)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.ThreadPoolValueTaskSource.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.IO.Strategies.BufferedFileStreamStrategy.WriteToNonSeekableAsync(ReadOnlyMemory`1 source, CancellationToken cancellationToken)
   at Microsoft.Playwright.Transport.StdIOTransport.SendAsync(Byte[] message) in /_/src/Playwright/Transport/StdIOTransport.cs:line 102
  Source=Microsoft.Playwright
