### ISSUE TITLE
[Question]: How to install playwright on target VM in CD pipeline

### ISSUE THREAD

**Issue by Liero** [microsoft/playwright-dotnet#1828] opened 2021-11-14 11:13 UTC
### Your question

I have a standard CI/CD Azure DevOps pipelines.

- Build pipeline that builds and publishes my projects and uploads build artifacts.
- Release pipeline, that runs on agent on my deployment VM, downloads the build artifacts and runs integration tests.

I have two questions:

1. How to install playwright browsers and drivers on deployment VM?

   The docs says:
    ```
   dotnet tool install --global Microsoft.Playwright.CLI
   playwright install
   ```
   but that does not work, because it requires a project or solution:

   > Couldn't find project using Playwright. Ensure a project or a solution exists in `C:\users\myuser`, or provide another path using -p.

   I only have my build artifacts (binaries) on deployment VM. No sources, no csproj...

2. How to exclude NodeJS from .playwright folder and use installed NodeJS?
    
    Currently, the PackageReference creates .playwright folder in output directory and it includes NodeJS binaries for all supported platforms. These NodeJS binaries are required .playwright folder in order to run tests, which means I have to upload them to build artifacts in my build pipeline and download them in release pipeline. Having couple of such projects, I have cca 1GB of binaries uploaded and downloaded with each release. Each release have 3 stages (environments), and each need to download the build artifacts, so it makes 3GB of additional download.
    
![image](https://user-images.githubusercontent.com/3494407/141678453-67ec77b3-c2f0-4bc4-b266-79f14f97b45e.png)

   The NodeJS is installed locally anyway, so I don't need these libraries anyway. How can I use locally installed NodeJS instead of `.playwright/node`?

**Comment by fr4gles** [comment] 2021-11-19 14:46
We have this steps https://github.com/microsoft/playwright-dotnet/issues/1788#issuecomment-937524114 successfully running in our CI/CD deployment in Azure DevOps

**Comment by Liero** [comment] 2021-11-21 09:43
#fr4gles: Thanks. That would be an answer for my first question. 

There is still the problem with gigabytes of node binaries copied multiple times.

**Comment by TanayParikh** [comment] 2021-12-01 21:10
I'm having issues getting a working playwright installation within the CI environment as well. I don't have a `csproj` / `sln` (just the built binaries). I have confirmed that `Microsoft.Playwright.dll` is one of the binaries in the directory. 

I've tried `Microsoft.Playwright.Program.Main(new[] { "install" })`, but I get:

```
Exception installing playwright: System.ComponentModel.Win32Exception (2): An error occurred trying to start process '/private/tmp/helix/working/BE9309F1/w/990A089B/e/RunTests/bin/Debug/net7.0/.playwright/node/mac/playwright.sh' with working directory '/private/tmp/helix/working/BE9309F1/w/990A089B/e'. No such file or directory
   at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at Microsoft.Playwright.Program.Run(String[] args)
   at Microsoft.Playwright.Program.Main(String[] args)
   at RunTests.TestRunner.InstallPlaywrightAsync() in /private/tmp/helix/working/BE9309F1/w/990A089B/e/RunTests/TestRunner.cs:line 120
```

I've even tried hacking around the [`.sln` check](https://github.com/microsoft/playwright-dotnet/blob/d734cbe3158bcd1282dcbf63adb216802b20cf69/src/Playwright.CLI/Program.cs#L55-L65) by creating a temp empty `sln` file (note I know `Microsoft.Playwright.dll` is present). Also, I fully recognize this is a terrible idea but wanted to see if that check may be the issue. However, I'm still getting `Microsoft.Playwright is missing required assets. Please ensure to build your project before running` afterwards.

Any tips?

**Comment by mxschmitt** [comment] 2022-01-17 10:42
There are currently three ways of installing the browsers / instructing the Playwright CLI.
1) using the recommended method: running the powershell script:
`pwsh bin\Debug\netX\playwright.ps1 install`
2) using the legacy Playwright CLI (we continue to maintain it but won't advertise it, since its global and not project specific which has drawbacks when multiple Playwright versions or language bindings are used)
```
dotnet tool install --global Microsoft.Playwright.CLI
playwright install
```
3) using it inline and calling the exposed Program class to run the CLI. (this was not intentionally exposed, we won't remove / hide it since people are using it and we don't want to break them.)
`Microsoft.Playwright.Program.Main(new[] {"install"});`

There is currently no official way of removing the Node.js installation. Feel free to upvote #1850 for that.

Closing since its answered.

**Closed by mxschmitt** 2022-01-17 10:42 UTC
