### ISSUE TITLE
 [BUG] Can't call CloseAsync on Browser after it's been called on Context

### ISSUE THREAD

**Issue by sjd23** [microsoft/playwright-dotnet#2716] opened 2023-10-03 09:40 UTC
### System info
- Playwright Version: [v1.38.]
- Operating System: [Windows 11]
- Browser: [Chromium]
- Other info:

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Test file (self-contained)**

```cs
        using var playwright = await Playwright.CreateAsync();
        await using var browser = await playwright.Chromium.LaunchAsync();
        await using var context = await browser.NewContextAsync();

        var page = await context.NewPageAsync();
        await page.GotoAsync("http://google.com");
        await page.WaitForTimeoutAsync(3000);

        await context.CloseAsync();
        await browser.CloseAsync();
```

**Steps**
- Execute the above code

**Expected**

No errors

**Actual**

Exception specifically after `browser.CloseAsync()` is called: 

```
Microsoft.Playwright.PlaywrightException: Target page, context or browser has been closed
   at Microsoft.Playwright.Transport.Connection.InnerSendMessageToServerAsync[T](String guid, String method, Dictionary`2 dictionary, Boolean keepNulls) in /_/src/Playwright/Transport/Connection.cs:line 192
   at Microsoft.Playwright.Transport.Connection.WrapApiCallAsync[T](Func`1 action, Boolean isInternal) in /_/src/Playwright/Transport/Connection.cs:line 515
   at Microsoft.Playwright.Core.Browser.CloseAsync() in /_/src/Playwright/Core/Browser.cs:line 79
```

I suspected that this could be because `CloseAsync` isn't safe to call twice and maybe the automatic disposal (due to `using`s above) causes conflicts, but I believe I'm using it correctly from what I can tell in other issues here and from the actual XML comments on the browser and context objects themselves. The browser actually appears to close as soon as I call `context.CloseAsync()` and I don't see any issues if I comment out the `browser.CloseAsync()` line, but this doesn't make much sense to me given the documentation.

**Comment by mxschmitt** [comment] 2023-10-04 13:35
Do you execute it using `dotnet run`? Do you have any special flags set in your csproj file? I tried to reproduce it with the code above but was not able to reproduce it.

We catch it here and swallow the error, so not sure whats happening in your case: https://github.com/microsoft/playwright-dotnet/blob/fba50171680ba0bfc1c267bb5b9c4e743bb8b186/src/Playwright/Core/Browser.cs#L83

**Comment by sjd23** [comment] 2023-10-05 05:37
I am using Rider and executing it by clicking Debug/Run on the default web API project which only has one method, the body of which I have copied above. The same problem exists when I run it as a unit test. The only difference is that I am not actually using google.com - I just replaced our company's website with that for the example. 

I stepped through the exception and could see that it's "internally" calling `DisposeAsync` just before failing, so I'm again thinking there's some conflict because of one of the `await using`s I have above.

**Comment by mxschmitt** [comment] 2023-10-05 23:35
Yes the error happens during `Browser.CloseAsync()` which is [`Browser.DisposeAsync()`](https://github.com/microsoft/playwright-dotnet/blob/fba50171680ba0bfc1c267bb5b9c4e743bb8b186/src/Playwright/Core/Browser.cs#L189). But it should get silently catched as per https://github.com/microsoft/playwright-dotnet/issues/2716#issuecomment-1746894425.

I unfortunately don't have Rider, so I cannot reproduce using this IDE.

**Comment by sjd23** [comment] 2023-10-05 23:51
I'll add my own try catch then and try to provide any other details that might somehow be helpful.

**Comment by mxschmitt** [comment] 2023-10-09 08:07
Maybe you have an option enabled to see also catched exceptions, some IDEs allow that, maybe [this](https://www.jetbrains.com/help/rider/Debugging_Exceptions.html#exception-breakpoints) helps.

**Comment by mxschmitt** [comment] 2023-10-19 15:12
Closing since this looks more like an issue with the IDE rather than a Playwright for .NET issue.

**Closed by mxschmitt** 2023-10-19 15:12 UTC
Labels: triaging

**Comment by sjd23** [comment] 2023-10-21 05:23
I haven't changed any settingsbas it looked like I didn't have any of those enabled, but I also haven't noticed any issuss while running the same code with a try/catch and putting a breakpoint within the catch. So I'll just let it boil down to environmental issues.
