### ISSUE TITLE
[Playwright][NuGet 1.8.1 Installation][Core Class Library Project][BUG]Bindings Refer To Mainline's Directory Path Not Library'

### ISSUE THREAD

**Issue by OneVideo** [microsoft/playwright-dotnet#2002] opened 2022-02-09 17:05 UTC

**Comment by pavelfeldman** [comment] 2022-02-09 19:24
Could you provide exact steps to reproduce the issue?

**Comment by OneVideo** [comment] 2022-02-09 22:34
Roll Your Own:
VS 2019: New project C# ConsoleApp .NET Framework Version 4.6.2
Add new project C# Class Library for .NET Core and .NET Standard; Target Framework .Net Core 2.1 (specified as the base requirement of the Playwright NuGet Package)
Revise Library class as static and add a async static "Hello World" TestMe function.
Multitarget Library project to     <TargetFrameworks>netcoreapp2.1;net462</TargetFrameworks>
Revise Mainline ConsoleApp to consume the TestMe and add a Project reference to the Class Library.
Compile and validate.
NuGet install Microsoft.Playwright into Library project
Add   <PropertyGroup>    <SuppressTfmSupportBuildWarnings>true</SuppressTfmSupportBuildWarnings>  </PropertyGroup> to .csproj for Library project
Insert into Library class .cs:
	using Microsoft.Playwright
  and into the TestMe
                IPlaywright playwright = await Playwright.CreateAsync();
                IBrowser browser = await playwright.Chromium.LaunchAsync();
Rebuild and validate no compile errors.
Debug breakpoint and step through call to CreateAsync()
Exception thrown (can catch in a Try{} or observe report upon return to caller.)



Or .sln Zipped in the attached archive:

**Comment by OneVideo** [comment] 2022-02-15 21:31
> Could you provide exact steps to reproduce the issue?

Dude: a) was that adequate response?  b) what, please, is the cadence on the team's responding and fixing?  Timelines here are not open-ended ...

**Comment by pavelfeldman** [comment] 2022-02-15 22:16
> a) was that adequate response?

I think so, but since it has a bunch of steps with ++ and +-, it'll wait for someone to find time to parse it. Cloning a repo with a .net project that we can run on Win/macOS/Linux would lower that repro barrier significantly, so that we could actually take a look.

> b) what, please, is the cadence on the team's responding and fixing?

There is no defined cadence, it all depends on the urgency of the issue. If the issue is a regression or has 20+ upvotes, it gets sorted out fairly rapidly. Otherwise, it might hang there for 6 months and get closed due to limited demand.

**Comment by OneVideo** [comment] 2022-02-15 22:51
> > a) was that adequate response?
> 
> I think so, but since it has a bunch of steps with ++ and +-, it'll wait for someone to find time to parse it. Cloning a repo with a .net project that we can run on Win/macOS/Linux would lower that repro barrier significantly, so that we could actually take a look.
> 
> > b) what, please, is the cadence on the team's responding and fixing?
> 
> There is no defined cadence, it all depends on the urgency of the issue. If the issue is a regression or has 20+ upvotes, it gets sorted out fairly rapidly. Otherwise, it might hang there for 6 months and get closed due to limited demand.

The URL to the .zip is a Visual Studio 2019 project that is already setup to show the problem.  Your colleague Max Schmitt (mxschmitt) downloaded it a few days back, so you can be confident it is clean.

**Comment by freesiafreesia** [comment] 2022-02-17 04:40
I've just bumped into the same error.
here's how.

1. Prepare a working project with playwright 1.18.x.
2. Upgrade playwright package to 1.19.0.
3. Press `F6` to build.
4. Downgrade playwright package to 1.18.1.
5. Press `F5` to run.

```
Microsoft.Playwright.PlaywrightException: 'Driver not found:
C:\Users\user\source\repos\myproject\myproject\bin\.playwright\node\win32_x64\playwright.cmd'
```
6. Do `build` -> `rebuild`.
7. Press `F5` to run.

It will be run successfully.
So, from my experience, if you try `rebuild` the error might gone.

**Comment by OneVideo** [comment] 2022-02-17 15:34
> I've just bumped into the same error. here's how.
> 
>     1. Prepare a working project with playwright 1.18.x.
> 
>     2. Upgrade playwright package to 1.19.0.
> 
>     3. Press `F6` to build.
> 
>     4. Downgrade playwright package to 1.18.1.
> 
>     5. Press `F5` to run.
> 
> 
> ```
> Microsoft.Playwright.PlaywrightException: 'Driver not found:
> C:\Users\user\source\repos\myproject\myproject\bin\.playwright\node\win32_x64\playwright.cmd'
> ```
> 
>     6. Do `build` -> `rebuild`.
> 
>     7. Press `F5` to run.
> 
> 
> It will be run successfully. So, from my experience, if you try `rebuild` the error might gone.

Thanks for suggesting.  Version 1.19 .. who knew?  Nevertheless, "[No joy in Mudville](https://poets.org/poem/casey-bat)"

**Comment by mxschmitt** [comment] 2022-04-05 13:59
This should be fixed now, @OneVideo and @freesiafreesia could you try to confirm if its working fine in 1.20.2?

**Comment by mxschmitt** [comment] 2022-10-12 18:34
Closing for now, please re-file if you still encounter issues.

**Closed by mxschmitt** 2022-10-12 18:34 UTC
