### ISSUE TITLE
[Question]: "Microsoft.Playwright assembly was found, but is missing required assets." - showing while trying to download browser binaries.

### ISSUE THREAD

**Issue by evilprince2009** [microsoft/playwright-dotnet#2362] opened 2022-11-01 11:36 UTC
### Your question

Trying to download browser binaries using `playwright.ps1 install` , but it shows `Microsoft.Playwright assembly was found, but is missing required assets. Please ensure to build your project before running Playwright tool.` Even after building my dotnet project the result is same as **[this](https://prnt.sc/pFJY5mkm2hzn)**. 

Any kind of help will be apricated, thanks.

**Comment by campersau** [comment] 2022-11-01 12:42
According to the documentation use `pwsh bin/Debug/netX/playwright.ps1 install` instead.
See https://playwright.dev/dotnet/docs/intro

**Comment by evilprince2009** [comment] 2022-11-01 14:11
> According to the documentation use `pwsh bin/Debug/netX/playwright.ps1 install` instead. See https://playwright.dev/dotnet/docs/intro

Doesn't seem to work exactly.

**Comment by feiyun0112** [comment] 2022-11-02 04:04
try to delete `C:\Users\{username}\AppData\Local\ms-playwright` folder and install again

**Comment by mxschmitt** [comment] 2022-11-04 18:38
What's your .NET version? Did you follow the intro or can you share a repro repository? What does `pwsh --version` yield to (shows the PowerShell version)? Did you build it before with `dotnet build`?

**Comment by nguyendauit** [comment] 2022-11-23 09:27
@evilprince2009 Seem like you are running on MacOS. Not sure if this helps

- Go to `bin/debug/.playwright/node` folder. Note that .playwright is hidden folder.
- Make sure that under node, you will see folder called: "mac". Not "win32_x64" or "linux-x64".

If the folder is NOT mac, then try to delete your folder and run this command
`
dotnet publish --configuration Release -r osx-x64 --output temp-release-folder
cd temp-release-folder
.\playwright.ps1 install
`

Hope it helps. Cheers

**Comment by mxschmitt** [comment] 2022-11-30 16:59
Closing as per above since we were not able to reproduce it.

**Closed by mxschmitt** 2022-11-30 16:59 UTC
Labels: triaging

**Comment by gaelj** [comment] 2023-01-11 10:25
If it can help, I had the same problem because the `PlaywrightPlatform` in the `csproj` was wrong. Fixed it by setting it to `all`

**Comment by paulsuart** [comment] 2023-04-20 11:56
As @gaelj mentioned, adding this to the .csproj file that references playwright will do the trick:

```
<PropertyGroup>
  <PlaywrightPlatform>all</PlaywrightPlatform>
</PropertyGroup>
```

I was building on Windows, copying files in a docker build and attempting to run `pwsh playwright.ps1 install chromium` on Linux and getting the error reported by the OP.

Adding `<PlaywrightPlatform>all</PlaywrightPlatform>` solved it.

**Comment by igor-svirid** [comment] 2023-04-20 14:03
@paulsuart but it doesn't work for me... struggling with this issue for 3 days and still having this issue with the [following configuration
](https://www.screenpresso.com/=I321c)
also have seen that browsers should be automatically downloaded, but while running tests they say to run this command to download them, which doesn't work for me. Do you have any other ways to fix it?

as a workarounds for me were:
1. download browsers with "npx playwright install"
2. download browsers in code with the "Microsoft.Playwright.Program.Main(new[] { "install" });"

But i really hope to make it work without workarounds

**Comment by paulsuart** [comment] 2023-04-20 18:07
@igor-svirid we run the following two commands prior to running the tests (we only test with Chrome):

```
playwright.ps1 install chromium
playwright.ps1 install-deps chromium
```

Hope this helps.

**Comment by igor-svirid** [comment] 2023-04-21 07:57
@paulsuart, unfortunately no, but i've played with the PlaywrightNUnit versions and noticed that this command allows me to download all browsers till the version 1.25.0([here](https://www.screenpresso.com/=WJtab)), but once i'm installing nuget PlaywrightNUnit with version 1.26.0 and above - i'm getting [this error](https://www.screenpresso.com/=fgqfg)

**Comment by ytodorov** [comment] 2023-06-05 07:20
> As @gaelj mentioned, adding this to the .csproj file that references playwright will do the trick:
> 
> ```
> <PropertyGroup>
>   <PlaywrightPlatform>all</PlaywrightPlatform>
> </PropertyGroup>
> ```
> 
> I was building on Windows, copying files in a docker build and attempting to run `pwsh playwright.ps1 install chromium` on Linux and getting the error reported by the OP.
> 
> Adding `<PlaywrightPlatform>all</PlaywrightPlatform>` solved it.

This helped me. Thank you! I lost 6 hours searching for this solution.

**Comment by milkyjoe90** [comment] 2023-07-24 11:00
> > As @gaelj mentioned, adding this to the .csproj file that references playwright will do the trick:
> > ```
> > <PropertyGroup>
> >   <PlaywrightPlatform>all</PlaywrightPlatform>
> > </PropertyGroup>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I was building on Windows, copying files in a docker build and attempting to run `pwsh playwright.ps1 install chromium` on Linux and getting the error reported by the OP.
> > Adding `<PlaywrightPlatform>all</PlaywrightPlatform>` solved it.
> 
> This helped me. Thank you! I lost 6 hours searching for this solution.

This has also solved the problem for me - it appears to have been introduced in 1.33.0, 1.32 and below were all fine without this entry.

**Comment by jidmadhu** [comment] 2023-10-10 06:58
Added this line resolved my issue: `Program.Main(new[] { "install" });`

Example: for NUnit
```
[SetUp]
    public Task SetUp()
    {
        int exitCode = Program.Main(new[] { "install" });
        if (exitCode != 0)
        {
            throw new InvalidOperationException($"Playwright exited with code {exitCode}");
        }

        return Task.CompletedTask;
    }
```

**Comment by maximilianschlipf** [comment] 2023-10-24 08:33
Unfortunately I'm not able to solve this issue on a Mac (Ventura 13.0) using .NET 7.0. Modifying the .csproj file did not do it for me.

**Comment by fozzie63** [comment] 2024-01-10 10:33
Did anyone resolve this? I'm on Mac 12.6 using .NET 7.0 and I amended the .csproj

**Comment by MarianKrkosMews** [comment] 2024-04-15 07:42
1) Removed local repo, did clean clone and rebuild solution and didn't help.
2) Update of Playwright nugets didn't help.
3) Removal and new installation of Microsoft.Playwright and Microsoft.Playwright.NUnit nuget packages solved the issue.

**Comment by zxcnebuster** [comment] 2024-05-04 19:47
> <PlaywrightPlatform>all</PlaywrightPlatform>

did the trick for me, thanks

**Comment by ozgurcubuk** [comment] 2025-03-12 19:51
developer experience for .net platform is extremly awful and costing hours to make it run on CI pipelines. in fact it was smooth for Node.js platform. Very bad.

**Comment by kmarek** [comment] 2025-04-10 15:10
I encountered issue `Microsoft.Playwright assembly was found, but is missing required assets. Please ensure to build your project before running Playwright tool.  `while setting up a pipeline on Azure DevOps, so I’m posting here in case it helps someone else 🙂

In Stage 1, I build the solution and upload the binaries to artifacts.
In the next stages (one per environment, as I want to re-use the same binaries), I download the binaries from the artifacts, install Playwright, and run the tests.

The issue was that I built the binaries on **Windows**, but was trying to install Playwright and run the tests on **Ubuntu**.
Changing the OS to be the same for both stages resolved the issue.

**Comment by Kavarera** [comment] 2025-11-29 14:49
if you on linux you need to do `chmod +x node` in **.playwright/linux-x64** folder. after that you can run it
